--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/PlayerVaults
branches:
- master
projects:
  PlayerVaults:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: pm5
        version: ^4.6.1
      - src: poggit/libasynql/libasynql
        branch: pm5
        version: ^4.1.1
...
