name: PlayerVaults
main: PlayerVaults\PlayerVaults
api: [3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.1, 3.1.1, 3.2]
version: 2.0
commands:
  playervault:
    default: true
    aliases: ["pv"]
permissions:
  playervaults.vault.1:
    default: true
