name: PlayerVaults
main: muqsit\playervaults\PlayerVaults
api: 4.0.0
version: 3.4.2
commands:
  playervault:
    permission: playervaults.command
    aliases: ["pv"]
permissions:
  playervaults.command:
    default: true
  playervaults.vault.1:
    default: true
  playervaults.others.edit:
    default: op
  playervaults.others.view:
    default: op