name: PlayerVaults
main: muqsit\playervaults\PlayerVaults
api: 5.0.0
version: 3.5.1
commands:
  playervault:
    permission: playervaults.command
    aliases: ["pv"]
permissions:
  playervaults.command:
    default: true
  playervaults.vault.1:
    default: true
  playervaults.others.edit:
    default: op
  playervaults.others.view:
    default: op