name: PlayerVaults
main: PlayerVaults\PlayerVaults
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 2.0
commands:
  playervault:
    default: true
    aliases: ["pv"]
permissions:
  playervaults.vault.1:
    default: true
